name: CI Tests

on: [push, pull_request]  # Запускать при пуше или PR

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # или windows-latest/macos-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive  # Важно для подмодулей!
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    - name: Configure CMake
      run: cmake -B build -S .
      
    - name: Build
      run: cmake --build build
      
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
