name: CI Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ build-essential

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Build project
      run: |
        cd build
        cmake --build . --parallel 2  # Убираем --target ALL_BUILD для Makefile

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Debug build files
      run: |
        cd build
        ls -la
        find . -name "*.cpp"  # Проверка, что исходники найдены
